package pro.sky.telegrambot.enums;

public enum UserCommand {

    START,
    CAT,
    DOG,
    MAIN_MENU,
    INFO_ABOUT_SHELTER,
    HOW_ADOPT_PET,
    SEND_REPORT,
    CALL_VOLUNTEER,
    SCHEDULE_AND_ADDRESS,
    LOCATION_MAP,
    REGISTRATION_PASS,
    SAFETY_PRECAUTIONS,
    SHARE_CONTACTS,
    RULES_FOR_MEETING,
    DOCUMENTS,
    TRANSPORTATION_RULES,
    HOME_IMPROVEMENT_FOR_SMALL_PET,
    HOME_IMPROVEMENT_FOR_BIG_PET,
    ADVICE_FROM_DOG_HANDLERS,
    DOG_HANDLERS,
    REJECTION_REASON,
    BACK,
    ABOUT_SHELTER,
}
