package pro.sky.telegrambot.enums;

public enum UserState {
    NEW_USER,
    START,
    CHOOSE_SHELTER,
    MAIN_MENU,
    CONVERSATION,
    INFO_ABOUT_SHELTER,
    SHARE_CONTACTS,
    HOW_ADOPT_PET,
    VIEWING_ANIMALS,
    SEND_REPORT,
    SELECT_ANIMAL_TO_REPORT,
    FILL_OUT_THE_REPORT,
    FILL_OUT_THE_REPORT_PHOTO,
    FILL_OUT_THE_REPORT_DIET,
    FILL_OUT_THE_REPORT_WELL_BEING,
    FILL_OUT_THE_REPORT_CHANGE_IN_BEHAVIOR,

}
