package pro.sky.telegrambot.enums;

public enum VolunteerCommand {

    AT_WORK,
    NOT_AT_WORK,
    CHECK_REPORTS,
    DECIDE_ON_PROBATION,
    ACCEPT_REPORT,
    DENY_REPORT,
    FINISH_VIEWING_REPORTS,
    ALLOW_ADOPTION,
    REFUSE_ADOPTION,
    EXTEND_FOR_FOURTEEN_DAYS,
    EXTEND_FOR_THIRTY_DAYS,
    FINISH_VIEWING_DECIDE_ON_PROBATION,
    OVERDUE_REPORTS,
    BACK,
}
